CREATE TABLE IF NOT EXISTS ROLES (
    ROLE_ID INTEGER PRIMARY KEY,
    ROLE_LABEL VARCHAR
);

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    ROLE_ID INTEGER REFERENCES ROLES (ROLE_ID),
    USER_NAME VARCHAR,
    EMAIL VARCHAR,
    PASSWORD VARCHAR,
    APPROVED BOOLEAN
);

CREATE TABLE IF NOT EXISTS ACCESSES (
    ACCESS_ID INTEGER PRIMARY KEY,
    ACCESS_LABEL VARCHAR
);

CREATE TABLE IF NOT EXISTS PERMISSION_STATUSES (
    STATUS_ID INTEGER PRIMARY KEY,
    STATUS_LABEL VARCHAR
);

CREATE TABLE IF NOT EXISTS ACCESS_PERMISSIONS (
    PERMISSION_ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    USER_ID UUID REFERENCES USERS (USER_ID),
    ACCESS_ID INTEGER REFERENCES ACCESSES (ACCESS_ID),
    STATUS_ID INTEGER REFERENCES PERMISSION_STATUSES (STATUS_ID),
    NEAR_EXPIRATION BOOLEAN,
    EXPIRES_IN TIMESTAMP,
    GRANTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REVOKED_AT TIMESTAMP
);