CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID   UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    ROLE      VARCHAR,
    STATUS    VARCHAR,
    USER_NAME VARCHAR,
    EMAIL     VARCHAR,
    PASSWORD  VARCHAR,
    APPROVED  BOOLEAN
);

CREATE TABLE IF NOT EXISTS ACCESSES
(
    ACCESS_ID    INTEGER PRIMARY KEY,
    ACCESS_LABEL VARCHAR
);

CREATE TABLE IF NOT EXISTS ACCESS_PERMISSIONS
(
    PERMISSION_ID   UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    USER_ID         UUID REFERENCES USERS (USER_ID),
    ACCESS_ID       INTEGER REFERENCES ACCESSES (ACCESS_ID),
    STATUS          VARCHAR,
    NEAR_EXPIRATION BOOLEAN,
    EXPIRES_IN      TIMESTAMP,
    GRANTED_AT      TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
    REVOKED_AT      TIMESTAMP
);